// frontend-vidalytics/app/create-profile/page.tsx
"use client";

import Image from "next/image";
import React, { useState } from "react";

interface FormData {
  name: string;
  niche: string;
  contentType: string;
  uploadFrequency: string;
  videoLength: string;
  monetisationStatus: string;
  primaryGoal: string;
  additionalNotes: string;
}

export default function CreateProfilePage() {
  const [formData, setFormData] = useState<FormData>({
    name: "",
    niche: "",
    contentType: "",
    uploadFrequency: "",
    videoLength: "",
    monetisationStatus: "",
    primaryGoal: "",
    additionalNotes: "",
  });

  const [errors, setErrors] = useState<Partial<FormData>>({});

  const handleInputChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name as keyof FormData]) {
      setErrors((prev) => ({ ...prev, [name]: "" }));
    }
  };

  const validateForm = () => {
    const newErrors: Partial<FormData> = {};
    if (!formData.name.trim()) newErrors.name = "Name is required";
    if (!formData.niche) newErrors.niche = "Niche is required";
    if (!formData.contentType)
      newErrors.contentType = "Content type is required";
    if (!formData.uploadFrequency)
      newErrors.uploadFrequency = "Upload frequency is required";
    if (!formData.videoLength)
      newErrors.videoLength = "Video length is required";
    if (!formData.monetisationStatus)
      newErrors.monetisationStatus = "Monetisation status is required";
    if (!formData.primaryGoal)
      newErrors.primaryGoal = "Primary goal is required";
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (validateForm()) {
      console.log("Form submitted:", formData);
      // Handle form submission logic here
    }
  };

  const handleConnectYoutube = () => {
    // Handle YouTube connection logic here
    console.log("Connect YouTube account");
  };

  return (
    <div
      className="min-h-screen flex items-center justify-center p-4"
      style={{ backgroundColor: "#2d3748" }}
    >
      <div className="w-full max-w-6xl bg-white rounded-3xl shadow-2xl flex flex-col lg:flex-row overflow-hidden">
        {/* Left: Form Section */}
        <div className="flex-1 p-6 sm:p-8 lg:p-12 flex flex-col justify-center">
          {/* Back Button */}
          <button className="flex items-center text-gray-500 mb-6 hover:text-gray-700 w-fit transition-colors">
            <svg
              className="w-5 h-5 mr-2"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 18l-6-6 6-6"
              />
            </svg>
            Back
          </button>

          {/* Header */}
          <div className="mb-8">
            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900 mb-2">
              Welcome to{" "}
              <span className="inline-flex items-center font-bold text-[#7C3AED]">
                ✨Vidalytics
              </span>
            </h1>
            <p className="text-gray-600 text-sm sm:text-base lg:text-lg">
              Let&apos;s set up your channel profile to get personalised AI
              assistance
            </p>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-5">
            {/* Name Field */}
            <div>
              <label
                htmlFor="name"
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                What should I call you? <span className="text-pink-500">*</span>
              </label>
              <input
                type="text"
                id="name"
                name="name"
                className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.name ? "border-red-400" : "border-gray-300"}`}
                placeholder="Enter your name or how you'd like to be called"
                value={formData.name}
                onChange={handleInputChange}
              />
              {errors.name && (
                <span className="text-xs text-red-500 mt-1 block">
                  {errors.name}
                </span>
              )}
            </div>

            {/* Row 1: Niche and Content Type */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="niche"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Niche <span className="text-pink-500">*</span>
                </label>
                <select
                  id="niche"
                  name="niche"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.niche ? "border-red-400" : "border-gray-300"}`}
                  value={formData.niche}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="gaming">Gaming</option>
                  <option value="tech">Technology</option>
                  <option value="lifestyle">Lifestyle</option>
                  <option value="education">Education</option>
                  <option value="entertainment">Entertainment</option>
                  <option value="business">Business</option>
                  <option value="fitness">Fitness & Health</option>
                  <option value="other">Other</option>
                </select>
                {errors.niche && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.niche}
                  </span>
                )}
              </div>
              <div>
                <label
                  htmlFor="contentType"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Content Type <span className="text-pink-500">*</span>
                </label>
                <select
                  id="contentType"
                  name="contentType"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.contentType ? "border-red-400" : "border-gray-300"}`}
                  value={formData.contentType}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="tutorials">Tutorials</option>
                  <option value="reviews">Reviews</option>
                  <option value="vlogs">Vlogs</option>
                  <option value="entertainment">Entertainment</option>
                  <option value="educational">Educational</option>
                  <option value="live-streams">Live Streams</option>
                  <option value="shorts">YouTube Shorts</option>
                  <option value="other">Other</option>
                </select>
                {errors.contentType && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.contentType}
                  </span>
                )}
              </div>
            </div>

            {/* Row 2: Upload Frequency and Video Length */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="uploadFrequency"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Upload Frequency <span className="text-pink-500">*</span>
                </label>
                <select
                  id="uploadFrequency"
                  name="uploadFrequency"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.uploadFrequency ? "border-red-400" : "border-gray-300"}`}
                  value={formData.uploadFrequency}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="daily">Daily</option>
                  <option value="weekly">Weekly</option>
                  <option value="bi-weekly">Bi-weekly</option>
                  <option value="monthly">Monthly</option>
                  <option value="irregular">Irregular</option>
                </select>
                {errors.uploadFrequency && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.uploadFrequency}
                  </span>
                )}
              </div>
              <div>
                <label
                  htmlFor="videoLength"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Typical Video Length <span className="text-pink-500">*</span>
                </label>
                <select
                  id="videoLength"
                  name="videoLength"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.videoLength ? "border-red-400" : "border-gray-300"}`}
                  value={formData.videoLength}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="shorts">Shorts (&lt;1 min)</option>
                  <option value="short">Short (1-5 min)</option>
                  <option value="medium">Medium (5-15 min)</option>
                  <option value="long">Long (15-30 min)</option>
                  <option value="very-long">Very Long (30+ min)</option>
                </select>
                {errors.videoLength && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.videoLength}
                  </span>
                )}
              </div>
            </div>

            {/* Row 3: Monetisation Status and Primary Goal */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="monetisationStatus"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Monetisation Status <span className="text-pink-500">*</span>
                </label>
                <select
                  id="monetisationStatus"
                  name="monetisationStatus"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.monetisationStatus ? "border-red-400" : "border-gray-300"}`}
                  value={formData.monetisationStatus}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="not-monetized">Not Monetized</option>
                  <option value="applying">Applying for Monetization</option>
                  <option value="monetized">Monetized</option>
                  <option value="partner">YouTube Partner</option>
                </select>
                {errors.monetisationStatus && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.monetisationStatus}
                  </span>
                )}
              </div>
              <div>
                <label
                  htmlFor="primaryGoal"
                  className="block text-sm font-medium text-gray-700 mb-2"
                >
                  Primary Goal <span className="text-pink-500">*</span>
                </label>
                <select
                  id="primaryGoal"
                  name="primaryGoal"
                  className={`w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 ${errors.primaryGoal ? "border-red-400" : "border-gray-300"}`}
                  value={formData.primaryGoal}
                  onChange={handleInputChange}
                >
                  <option value="">Select</option>
                  <option value="subscribers">Grow Subscribers</option>
                  <option value="views">Increase Views</option>
                  <option value="engagement">Boost Engagement</option>
                  <option value="monetization">Maximize Revenue</option>
                  <option value="brand">Build Brand</option>
                  <option value="education">Educate Audience</option>
                  <option value="entertainment">Entertain Audience</option>
                </select>
                {errors.primaryGoal && (
                  <span className="text-xs text-red-500 mt-1 block">
                    {errors.primaryGoal}
                  </span>
                )}
              </div>
            </div>

            {/* Additional Notes */}
            <div>
              <label
                htmlFor="additionalNotes"
                className="block text-sm font-medium text-gray-700 mb-2"
              >
                Additional Notes
              </label>
              <textarea
                id="additionalNotes"
                name="additionalNotes"
                className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent transition-all duration-200 resize-none"
                placeholder="Write your note here"
                rows={3}
                value={formData.additionalNotes}
                onChange={handleInputChange}
              />
            </div>

            {/* YouTube Connection Section */}
            <div className="bg-gray-50 border border-gray-200 rounded-xl p-6 text-center">
              <h2 className="font-semibold text-gray-800 text-lg mb-2">
                Connect Your YouTube Channel
              </h2>
              <p className="text-sm text-gray-500 mb-4">
                Connect your YouTube account to automatically import your
                channel statistics
              </p>
              <button
                type="button"
                onClick={handleConnectYoutube}
                className="flex items-center justify-center gap-2 bg-white border border-red-400 text-red-500 font-semibold px-6 py-3 rounded-lg shadow-sm hover:bg-red-50 transition-colors mx-auto mb-2"
              >
                <svg
                  className="w-5 h-5"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M21.8 8.001c-.2-.801-.8-1.401-1.601-1.601C18.2 6 12 6 12 6s-6.2 0-8.2.4c-.8.2-1.4.8-1.6 1.601C2 10 2 12 2 12s0 2 .2 3.999c.2.801.8 1.401 1.6 1.601C5.8 18 12 18 12 18s6.2 0 8.2-.4c.8-.2 1.4-.8 1.6-1.601C22 14 22 12 22 12s0-2-.2-3.999zM10 15.5v-7l6 3.5-6 3.5z" />
                </svg>
                Connect YouTube Account
              </button>
              <p className="text-xs text-gray-400">
                Optional: You can connect later from Settings
              </p>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              className="w-full bg-gradient-to-r from-pink-500 to-purple-500 text-white font-bold py-4 rounded-xl shadow-lg hover:from-pink-600 hover:to-purple-600 transition-all duration-200 text-lg"
            >
              Complete Setup
            </button>
          </form>
        </div>

        {/* Right Side: Robot Image Section */}
        <div
          className="w-1/2 relative rounded-r-2xl overflow-hidden flex flex-col"
          style={{
            background: "linear-gradient(135deg, #0f172a 0%, #020617 100%)",
          }}
        >
          {/* Main Robot - Top Half */}
          <div className="flex-1 relative">
            <Image
              src="/BossAgent.png"
              alt="Friendly robot assistant with analytics charts"
              width={900}
              height={900}
              className="absolute inset-0 w-full h-full object-cover"
            />
          </div>

          {/* Other Agents - Bottom Half */}
          <div className="flex-1 relative flex flex-col justify-between p-6">
            {/* Text - positioned high up, just under Boss Agent */}
            <div className="flex-1 flex items-start justify-center pt-4">
              <h3
                className="text-white font-bold text-center leading-tight"
                style={{ fontSize: "4rem", lineHeight: "1.1" }}
              >
                Meet Boss Agent and his Agentic Workers
              </h3>
            </div>

            {/* Agent Avatars - stay at the bottom */}
            <div className="flex space-x-3 opacity-90 justify-center">
              <Image
                src="/Agent1.png"
                alt="Agent 1"
                width={100}
                height={100}
                className="rounded-full border-2 border-white/30 hover:scale-105 transition-transform"
              />
              <Image
                src="/Agent2.png"
                alt="Agent 2"
                width={100}
                height={100}
                className="rounded-full border-2 border-white/30 hover:scale-105 transition-transform"
              />
              <Image
                src="/Agent3.png"
                alt="Agent 3"
                width={100}
                height={100}
                className="rounded-full border-2 border-white/30 hover:scale-105 transition-transform"
              />
              <Image
                src="/Agent4.png"
                alt="Agent 4"
                width={100}
                height={100}
                className="rounded-full border-2 border-white/30 hover:scale-105 transition-transform"
              />
              <Image
                src="/Agent5.png"
                alt="Agent 5"
                width={100}
                height={100}
                className="rounded-full border-2 border-white/30 hover:scale-105 transition-transform"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-nuxt4/pages/create-profile.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-forest-900 via-forest-800 to-forest-700 relative overflow-hidden">
    <!-- Background Elements -->
    <div class="absolute inset-0">
      <div class="absolute top-20 left-20 w-72 h-72 bg-orange-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
      <div class="absolute top-40 right-20 w-72 h-72 bg-forest-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
      <div class="absolute bottom-20 left-40 w-72 h-72 bg-orange-400 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-4000"></div>
    </div>

    <div class="relative z-10 min-h-screen px-6">
      <div class="w-full max-w-7xl mx-auto -mt-12">
        <!-- MYTA Logo Header -->
        <div class="text-center -mt-16">
          <div class="flex items-center justify-center -mb-20">
            <img src="/MYTALogo.png" alt="MYTA Logo" class="w-[28rem] h-[28rem]">
          </div>

        </div>

        <!-- Boss Agent Naming -->
        <div class="mb-8">
          <h2 class="text-2xl font-semibold text-white text-center mb-6">Name Your Boss Agent</h2>
          <div class="max-w-md mx-auto">
            <div class="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
              <div class="flex items-center space-x-4 mb-4">
                <div class="w-16 h-16 rounded-xl overflow-hidden bg-white/20 flex items-center justify-center flex-shrink-0">
                  <img src="/BossAgent.png" alt="Boss Agent" class="w-full h-full object-cover">
                </div>
                <div class="flex-1">
                  <label for="agentName" class="block text-sm font-semibold text-white mb-2">
                    Boss Agent Name
                  </label>
                  <input
                    id="agentName"
                    v-model="formData.agentName"
                    type="text"
                    placeholder="e.g., Fred, Alex, Sarah..."
                    class="w-full p-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm"
                  >
                </div>
              </div>
              <p class="text-gray-300 text-sm text-center">
                Your Boss Agent will coordinate with specialized agents behind the scenes to help you grow your channel.
              </p>
            </div>
          </div>
        </div>

        <!-- Main Content Card -->
        <div class="bg-white/10 backdrop-blur-lg rounded-3xl border border-white/20 shadow-2xl overflow-hidden max-w-6xl mx-auto">
          <div class="grid lg:grid-cols-2 min-h-[500px]">
            <!-- Left Side - Form -->
            <div class="p-8 lg:p-12">
              <!-- Form Content -->
              <form @submit.prevent="handleSubmit" class="space-y-6">
                <!-- What drives you -->
                <div>
                  <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                    What drives you as a YouTuber?
                  </label>
                  <textarea
                    v-model="formData.motivation"
                    placeholder="Share what motivates you to create content..."
                    class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm resize-none"
                    rows="3"
                  ></textarea>
                </div>

                <!-- Niche and Content Type -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                      Niche
                    </label>
                    <select
                      v-model="formData.niche"
                      class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm"
                    >
                      <option value="" class="text-gray-800">Select your niche</option>
                      <option value="gaming" class="text-gray-800">Gaming</option>
                      <option value="tech" class="text-gray-800">Technology</option>
                      <option value="lifestyle" class="text-gray-800">Lifestyle</option>
                      <option value="education" class="text-gray-800">Education</option>
                      <option value="entertainment" class="text-gray-800">Entertainment</option>
                      <option value="business" class="text-gray-800">Business</option>
                      <option value="health" class="text-gray-800">Health & Fitness</option>
                      <option value="travel" class="text-gray-800">Travel</option>
                      <option value="food" class="text-gray-800">Food & Cooking</option>
                      <option value="music" class="text-gray-800">Music</option>
                      <option value="art" class="text-gray-800">Art & Design</option>
                      <option value="other" class="text-gray-800">Other</option>
                    </select>
                  </div>

                  <div>
                    <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                      Content Type
                    </label>
                    <select
                      v-model="formData.contentType"
                      class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm"
                    >
                      <option value="" class="text-gray-800">Select content type</option>
                      <option value="tutorials" class="text-gray-800">Tutorials</option>
                      <option value="vlogs" class="text-gray-800">Vlogs</option>
                      <option value="reviews" class="text-gray-800">Reviews</option>
                      <option value="entertainment" class="text-gray-800">Entertainment</option>
                      <option value="educational" class="text-gray-800">Educational</option>
                      <option value="live-streams" class="text-gray-800">Live Streams</option>
                      <option value="shorts" class="text-gray-800">YouTube Shorts</option>
                      <option value="music" class="text-gray-800">Music Videos</option>
                      <option value="comedy" class="text-gray-800">Comedy</option>
                      <option value="documentary" class="text-gray-800">Documentary</option>
                    </select>
                  </div>
                </div>

                <!-- Upload Frequency and Target Goal -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                      Upload Frequency
                    </label>
                    <select
                      v-model="formData.uploadFrequency"
                      class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm"
                    >
                      <option value="" class="text-gray-800">Select frequency</option>
                      <option value="daily" class="text-gray-800">Daily</option>
                      <option value="weekly" class="text-gray-800">Weekly</option>
                      <option value="bi-weekly" class="text-gray-800">Bi-weekly</option>
                      <option value="monthly" class="text-gray-800">Monthly</option>
                      <option value="irregular" class="text-gray-800">Irregular</option>
                    </select>
                  </div>

                  <div>
                    <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                      Target Goal
                    </label>
                    <select
                      v-model="formData.targetGoal"
                      class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm"
                    >
                      <option value="" class="text-gray-800">Select your goal</option>
                      <option value="subscribers" class="text-gray-800">Grow Subscribers</option>
                      <option value="views" class="text-gray-800">Increase Views</option>
                      <option value="engagement" class="text-gray-800">Boost Engagement</option>
                      <option value="monetization" class="text-gray-800">Monetization</option>
                      <option value="brand" class="text-gray-800">Build Brand</option>
                      <option value="community" class="text-gray-800">Build Community</option>
                    </select>
                  </div>
                </div>

                <!-- Additional Notes -->
                <div>
                  <label class="block text-sm font-semibold text-white mb-3 uppercase tracking-wide">
                    Additional Notes
                  </label>
                  <textarea
                    v-model="formData.additionalNotes"
                    placeholder="Tell us about your future plans..."
                    class="w-full p-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent backdrop-blur-sm resize-none"
                    rows="3"
                  ></textarea>
                </div>

                <!-- Submit Button -->
                <div class="pt-6">
                  <button
                    type="submit"
                    :disabled="!isFormValid || isConnecting"
                    class="w-full bg-gradient-to-r from-orange-500 to-orange-600 text-white font-bold py-4 px-8 rounded-xl hover:from-orange-600 hover:to-orange-700 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105 flex items-center justify-center gap-2"
                  >
                    <svg v-if="isConnecting" class="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                      <path class="opacity-75" fill="currentColor" d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    {{ isConnecting ? 'Connecting to YouTube...' : 'Connect Your YouTube Channel' }}
                  </button>
                </div>
              </form>
            </div>

            <!-- Right Side - Visual Content -->
            <div class="relative bg-gradient-to-br from-forest-600 to-orange-600 p-8 lg:p-12 flex items-center justify-center">
              <!-- AI Robot Illustration -->
              <div class="text-center">
                <h3 class="text-2xl font-bold text-white mb-6">
                  Meet Your AI Agents
                </h3>

                <!-- Agent Grid -->
                <div class="grid grid-cols-2 gap-4 max-w-md mx-auto">
                  <div
                    v-for="agent in agents"
                    :key="'sidebar-' + agent.id"
                    @click="selectAgent(agent.id)"
                    class="bg-white/10 backdrop-blur-lg rounded-2xl p-4 text-center cursor-pointer transition-all duration-300 hover:bg-white/20 hover:scale-105 border border-white/20"
                    :class="selectedAgent === agent.id ? 'scale-105' : ''"
                    :style="selectedAgent === agent.id ? {
                      backgroundColor: agent.color + '30',
                      borderColor: agent.color,
                      boxShadow: `0 0 30px ${agent.color}80`
                    } : {}"
                  >
                    <div class="w-12 h-12 mx-auto mb-2 rounded-xl overflow-hidden bg-white/20 flex items-center justify-center">
                      <img :src="agent.image" :alt="agent.name" class="w-full h-full object-cover">
                    </div>
                    <h4 class="text-white font-semibold mb-1 text-xs">{{ agent.name }}</h4>
                    <p class="text-gray-300 text-xs leading-tight">{{ agent.description }}</p>
                  </div>
                </div>

                <p class="text-gray-200 text-sm mt-6 leading-relaxed">
                  Choose your specialized AI agent to get personalized content strategies and growth insights.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'

// Remove the default layout with header and add guest middleware
definePageMeta({
  layout: false,
  middleware: 'guest'
})

// Agent data with images from the public folder - matching backend definitions
const agents = ref([
  {
    id: 'boss',
    name: 'Boss Agent',
    description: 'Strategic Leadership',
    image: '/BossAgent.png',
    color: '#FF6B35'
  },
  {
    id: 1,
    name: 'Alex',
    description: 'Analytics & Strategy',
    image: '/Alex.png',
    color: '#3b82f6'
  },
  {
    id: 2,
    name: 'Levi',
    description: 'Content Creation',
    image: '/Levi.png',
    color: '#eab308'
  },
  {
    id: 3,
    name: 'Maya',
    description: 'Audience Engagement',
    image: '/Maya.png',
    color: '#16a34a'
  },
  {
    id: 4,
    name: 'Zara',
    description: 'Growth & Optimization',
    image: '/Zara.png',
    color: '#a855f7'
  },
  {
    id: 5,
    name: 'Kai',
    description: 'Technical & SEO',
    image: '/Kai.png',
    color: '#dc2626'
  }
])

// Selected agent
const selectedAgent = ref('boss') // Default to Boss Agent

// Form data
const formData = ref({
  agentName: 'Fred', // Default name for Executive Agent
  motivation: '',
  niche: '',
  contentType: '',
  uploadFrequency: '',
  targetGoal: '',
  additionalNotes: '',
})

// Loading state for YouTube connection
const isConnecting = ref(false)

// Form validation
const isFormValid = computed(() => {
  return formData.value.agentName.trim() !== '' &&
         formData.value.motivation.trim() !== '' &&
         formData.value.niche !== '' &&
         formData.value.contentType !== ''
})

// Select agent function
const selectAgent = (agentId) => {
  selectedAgent.value = agentId
}

// Handle form submission
const handleSubmit = async () => {
  if (isFormValid.value && !isConnecting.value) {
    console.log('Form data:', {
      ...formData.value,
      selectedAgent: selectedAgent.value
    })

    // Save profile data (you might want to save this to a store or API)
    // For now, we'll just log it and proceed to YouTube connection

    try {
      isConnecting.value = true

      // Import and use the YouTube connection function
      const { connectYouTube } = await import('~/composables/useYouTubeChannel')
      await connectYouTube()
      // Note: connectYouTube will redirect to YouTube OAuth, then back to dashboard
    } catch (error) {
      console.error('Failed to connect YouTube:', error)
      // Fallback: navigate to dashboard anyway
      navigateTo('/dashboard')
    } finally {
      isConnecting.value = false
    }
  }
}
</script>

<style scoped>
/* Animation classes */
@keyframes blob {
  0% {
    transform: translate(0px, 0px) scale(1);
  }
  33% {
    transform: translate(30px, -50px) scale(1.1);
  }
  66% {
    transform: translate(-20px, 20px) scale(0.9);
  }
  100% {
    transform: translate(0px, 0px) scale(1);
  }
}

.animate-blob {
  animation: blob 7s infinite;
}

.animation-delay-2000 {
  animation-delay: 2s;
}

.animation-delay-4000 {
  animation-delay: 4s;
}

.animation-delay-1000 {
  animation-delay: 1s;
}

/* Agent card styles */
.agent-card.selected {
  @apply bg-white/30 border-orange-400 scale-105;
  box-shadow: 0 0 30px rgba(249, 115, 22, 0.5);
}

.agent-card:hover {
  transform: translateY(-5px) scale(1.05);
}

/* Custom scrollbar for textareas */
textarea::-webkit-scrollbar {
  width: 6px;
}

textarea::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 3px;
}

textarea::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 3px;
}

textarea::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}
</style>
