// frontend-new/src/pages/Pillars.tsx
import { useState } from 'react'
import { LineChart, Line, XAxis, YAxis, ResponsiveContainer } from 'recharts'
import Card from '@/components/common/Card'
import Button from '@/components/common/Button'
import { MoreHorizontal, TrendingUp, TrendingDown } from 'lucide-react'

interface PillarData {
  id: string
  name: string
  icon: string
  color: string
  videos: number
  views: number
  watchTime: number
  revenue: number
  viewsChange: number
  watchTimeChange: number
  revenueChange: number
  createdAgo: string
  chartData: Array<{ month: string; value: number }>
  tags: string[]
  topPerformingContent: string
  insight: string
}

const mockPillarsData: PillarData[] = [
  {
    id: 'game-development',
    name: 'Game Development',
    icon: '🎮',
    color: 'from-blue-500 to-cyan-400',
    videos: 12,
    views: 248300,
    watchTime: 14.2,
    revenue: 3842,
    viewsChange: -3.5,
    watchTimeChange: -2.1,
    revenueChange: -6.8,
    createdAgo: '4 months ago',
    chartData: [
      { month: 'Feb', value: 180000 },
      { month: 'Mar', value: 220000 },
      { month: 'Apr', value: 235000 },
      { month: 'May', value: 248000 },
      { month: 'Jun', value: 248300 }
    ],
    tags: ['Unity', 'C#', 'Indie Games', 'Tutorials'],
    topPerformingContent: 'Top performing content pillar',
    insight: 'Strong technical content with consistent growth'
  },
  {
    id: 'game-reviews',
    name: 'Game Reviews',
    icon: '⭐',
    color: 'from-purple-500 to-pink-400',
    videos: 8,
    views: 166700,
    watchTime: 8.6,
    revenue: 2156,
    viewsChange: -6.4,
    watchTimeChange: -3.2,
    revenueChange: -1.1,
    createdAgo: '3 months ago',
    chartData: [
      { month: 'Feb', value: 120000 },
      { month: 'Mar', value: 140000 },
      { month: 'Apr', value: 155000 },
      { month: 'May', value: 162000 },
      { month: 'Jun', value: 166700 }
    ],
    tags: ['Reviews', 'AAA Games', 'Indie', 'First Impressions'],
    topPerformingContent: 'Consistent growth in audience retention',
    insight: 'High engagement from loyal audience base'
  },
  {
    id: 'gaming-tips',
    name: 'Gaming Tips',
    icon: '💡',
    color: 'from-orange-500 to-yellow-400',
    videos: 15,
    views: 203500,
    watchTime: 10.1,
    revenue: 2937,
    viewsChange: -1.7,
    watchTimeChange: -8.5,
    revenueChange: -6.5,
    createdAgo: '5 months ago',
    chartData: [
      { month: 'Feb', value: 150000 },
      { month: 'Mar', value: 175000 },
      { month: 'Apr', value: 190000 },
      { month: 'May', value: 200000 },
      { month: 'Jun', value: 203500 }
    ],
    tags: ['Tips & Tricks', 'Strategy', 'Guides', 'Competitive'],
    topPerformingContent: 'High engagement from returning viewers',
    insight: 'Educational content with strong retention'
  },
  {
    id: 'gaming-news',
    name: 'Gaming News',
    icon: '📰',
    color: 'from-red-500 to-pink-400',
    videos: 6,
    views: 97200,
    watchTime: 4.3,
    revenue: 843,
    viewsChange: -3.6,
    watchTimeChange: -5.2,
    revenueChange: -3.5,
    createdAgo: '2 months ago',
    chartData: [
      { month: 'Feb', value: 85000 },
      { month: 'Mar', value: 110000 },
      { month: 'Apr', value: 102000 },
      { month: 'May', value: 95000 },
      { month: 'Jun', value: 97200 }
    ],
    tags: ['Industry News', 'Updates', 'Releases', 'Events'],
    topPerformingContent: 'Needs improvement in content strategy',
    insight: 'Trending content requires timely coverage'
  }
]

function PillarCard({ pillar }: { pillar: PillarData }) {
  const formatViews = (views: number) => {
    if (views >= 1000000) return `${(views / 1000000).toFixed(1)}M`
    if (views >= 1000) return `${(views / 1000).toFixed(1)}K`
    return views.toString()
  }

  const formatWatchTime = (hours: number) => {
    if (hours >= 1000) return `${(hours / 1000).toFixed(1)}K hrs`
    return `${hours}K hrs`
  }

  const formatRevenue = (revenue: number) => {
    return `$${revenue.toLocaleString()}`
  }

  const getChangeIcon = (change: number) => {
    if (change > 0) return <TrendingUp className="w-3 h-3 text-green-400" />
    return <TrendingDown className="w-3 h-3 text-red-400" />
  }

  const getChangeColor = (change: number) => {
    return change > 0 ? 'text-green-400' : 'text-red-400'
  }

  return (
    <Card className="p-6 bg-dark-900 border-dark-700">
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${pillar.color} flex items-center justify-center text-lg`}>
            {pillar.icon}
          </div>
          <div>
            <h3 className="font-semibold text-white">{pillar.name}</h3>
            <p className="text-sm text-dark-400">{pillar.videos} videos • Created {pillar.createdAgo}</p>
          </div>
        </div>
        <button className="p-1 text-dark-400 hover:text-white">
          <MoreHorizontal className="w-4 h-4" />
        </button>
      </div>

      <div className="grid grid-cols-3 gap-4 mb-6">
        <div>
          <div className="text-sm text-dark-400 mb-1">Views</div>
          <div className="text-xl font-bold text-white">{formatViews(pillar.views)}</div>
          <div className={`text-xs flex items-center gap-1 ${getChangeColor(pillar.viewsChange)}`}>
            {getChangeIcon(pillar.viewsChange)}
            {Math.abs(pillar.viewsChange).toFixed(1)}%
          </div>
        </div>
        <div>
          <div className="text-sm text-dark-400 mb-1">Watch Time</div>
          <div className="text-xl font-bold text-white">{formatWatchTime(pillar.watchTime)}</div>
          <div className={`text-xs flex items-center gap-1 ${getChangeColor(pillar.watchTimeChange)}`}>
            {getChangeIcon(pillar.watchTimeChange)}
            {Math.abs(pillar.watchTimeChange).toFixed(1)}%
          </div>
        </div>
        <div>
          <div className="text-sm text-dark-400 mb-1">Revenue</div>
          <div className="text-xl font-bold text-white">{formatRevenue(pillar.revenue)}</div>
          <div className={`text-xs flex items-center gap-1 ${getChangeColor(pillar.revenueChange)}`}>
            {getChangeIcon(pillar.revenueChange)}
            {Math.abs(pillar.revenueChange).toFixed(1)}%
          </div>
        </div>
      </div>

      <div className="mb-6">
        <ResponsiveContainer width="100%" height={120}>
          <LineChart data={pillar.chartData}>
            <XAxis 
              dataKey="month" 
              axisLine={false}
              tickLine={false}
              tick={{ fontSize: 12, fill: '#6B7280' }}
            />
            <YAxis hide />
            <Line 
              type="monotone" 
              dataKey="value" 
              stroke={pillar.color.includes('blue') ? '#3B82F6' : 
                     pillar.color.includes('purple') ? '#8B5CF6' :
                     pillar.color.includes('orange') ? '#F59E0B' : '#EF4444'}
              strokeWidth={2}
              dot={false}
            />
          </LineChart>
        </ResponsiveContainer>
      </div>

      <div className="flex flex-wrap gap-1 mb-4">
        {pillar.tags.map((tag) => (
          <span 
            key={tag} 
            className="px-2 py-1 text-xs bg-dark-800 text-dark-300 rounded"
          >
            {tag}
          </span>
        ))}
      </div>

      <div className="text-sm text-dark-400 mb-4">{pillar.topPerformingContent}</div>

      <div className="flex gap-2">
        <Button size="sm" className="flex-1">
          View Details
        </Button>
        <Button size="sm" variant="secondary">
          Create Content
        </Button>
      </div>
    </Card>
  )
}

export default function Pillars() {
  const [pillars] = useState<PillarData[]>(mockPillarsData)
  const [timeRange, setTimeRange] = useState('Last 30 days')

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold mb-2">Content Pillars</h1>
          <p className="text-dark-400">
            Analyze and optimize your content strategy
          </p>
        </div>
        <div className="flex items-center gap-3">
          <select 
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value)}
            className="px-3 py-2 bg-dark-800 border border-dark-600 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            <option>Last 30 days</option>
            <option>Last 60 days</option>
            <option>Last 90 days</option>
          </select>
          <Button>
            Add Pillar
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {pillars.map((pillar) => (
          <PillarCard key={pillar.id} pillar={pillar} />
        ))}
      </div>

      <Card className="p-6 bg-gradient-to-r from-purple-600/20 to-blue-600/20 border-purple-500/30">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-blue-500 rounded-lg flex items-center justify-center">
            🤖
          </div>
          <div>
            <h3 className="font-semibold text-white">AI Suggested: Metaverse Coverage</h3>
            <span className="text-xs bg-blue-500 text-white px-2 py-0.5 rounded">NEW</span>
          </div>
        </div>
        <p className="text-sm text-dark-300 mb-4">
          Based on trending topics and your audience interests, consider creating content about metaverse gaming platforms.
        </p>
        <Button size="sm" variant="secondary">
          Explore Suggestion
        </Button>
      </Card>
    </div>
  )
}

// frontend-nuxt4/app/pages/pillars.vue
<template>
  <div class="min-h-screen bg-forest-900 text-white">


    <!-- Main Content Area -->
    <div class="p-6 pt-32">
      <!-- Header -->
      <div class="mb-6 flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold text-white mb-2">Content Pillars</h1>
          <p class="text-gray-400">Analyze and optimize your content strategy</p>
        </div>
        <div class="flex items-center space-x-4">
          <div class="text-sm text-gray-400">Last 30 days</div>
          <button
            class="flex items-center space-x-2 rounded-lg bg-orange-500 px-4 py-2 text-white transition-colors hover:bg-orange-600"
          >
            <svg class="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
              <path
                fill-rule="evenodd"
                d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
                clip-rule="evenodd"
              />
            </svg>
            <span>Add Pillar</span>
          </button>
        </div>
      </div>

      <!-- Content Pillars Grid -->
      <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <!-- Game Development Pillar -->
        <div class="rounded-xl bg-forest-800 p-6">
          <div class="mb-4 flex items-center justify-between">
            <div class="flex items-center space-x-3">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-500">
                <svg class="h-6 w-6 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                </svg>
              </div>
              <div>
                <h3 class="text-lg font-semibold text-white">Game Development</h3>
                <p class="text-sm text-gray-400">3 Videos • Created 4 months ago</p>
              </div>
            </div>
            <button class="text-gray-400 hover:text-white">
              <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                <path
                  d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
                />
              </svg>
            </button>
          </div>

          <!-- Metrics -->
          <div class="mb-6 grid grid-cols-3 gap-4">
            <div>
              <div class="text-2xl font-bold text-white">248.3K</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +12.5%
              </div>
              <div class="text-xs text-gray-400">Revenue</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">14.2K hrs</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +8.2%
              </div>
              <div class="text-xs text-gray-400">Watch Time</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">93,842</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +15.3%
              </div>
              <div class="text-xs text-gray-400">Subscribers</div>
            </div>
          </div>

          <!-- Chart Area -->
          <div class="relative mb-4 h-32">
            <svg class="h-full w-full" viewBox="0 0 300 100">
              <defs>
                <linearGradient id="blueGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" style="stop-color: #3b82f6; stop-opacity: 0.3" />
                  <stop offset="100%" style="stop-color: #3b82f6; stop-opacity: 0" />
                </linearGradient>
              </defs>
              <path
                d="M0,80 Q50,70 100,60 T200,45 T300,35"
                stroke="#3B82F6"
                stroke-width="2"
                fill="none"
              />
              <path
                d="M0,80 Q50,70 100,60 T200,45 T300,35 L300,100 L0,100 Z"
                fill="url(#blueGradient)"
              />
            </svg>
          </div>

          <!-- Action Buttons -->
          <div class="flex items-center justify-between">
            <div class="text-sm text-gray-400">Top performing content pillar</div>
            <div class="flex space-x-2">
              <button class="px-3 py-1 text-sm text-gray-300 hover:text-white">View Details</button>
              <button class="rounded bg-orange-500 px-3 py-1 text-sm text-white hover:bg-orange-600">
                Create Content
              </button>
            </div>
          </div>
        </div>

        <!-- Game Reviews Pillar -->
        <div class="rounded-xl bg-forest-800 p-6">
          <div class="mb-4 flex items-center justify-between">
            <div class="flex items-center space-x-3">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-500">
                <svg class="h-6 w-6 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                  />
                </svg>
              </div>
              <div>
                <h3 class="text-lg font-semibold text-white">Game Reviews</h3>
                <p class="text-sm text-gray-400">8 Videos • Created 3 months ago</p>
              </div>
            </div>
            <button class="text-gray-400 hover:text-white">
              <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                <path
                  d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
                />
              </svg>
            </button>
          </div>

          <!-- Metrics -->
          <div class="mb-6 grid grid-cols-3 gap-4">
            <div>
              <div class="text-2xl font-bold text-white">186.7K</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +9.8%
              </div>
              <div class="text-xs text-gray-400">Revenue</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">6.9K hrs</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +6.1%
              </div>
              <div class="text-xs text-gray-400">Watch Time</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">52,156</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +11.2%
              </div>
              <div class="text-xs text-gray-400">Subscribers</div>
            </div>
          </div>

          <!-- Chart Area -->
          <div class="relative mb-4 h-32">
            <svg class="h-full w-full" viewBox="0 0 300 100">
              <defs>
                <linearGradient id="purpleGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" style="stop-color: #8b5cf6; stop-opacity: 0.3" />
                  <stop offset="100%" style="stop-color: #8b5cf6; stop-opacity: 0" />
                </linearGradient>
              </defs>
              <path
                d="M0,85 Q50,75 100,65 T200,50 T300,40"
                stroke="#8B5CF6"
                stroke-width="2"
                fill="none"
              />
              <path
                d="M0,85 Q50,75 100,65 T200,50 T300,40 L300,100 L0,100 Z"
                fill="url(#purpleGradient)"
              />
            </svg>
          </div>

          <!-- Action Buttons -->
          <div class="flex items-center justify-between">
            <div class="text-sm text-gray-400">Consistent growth in audience retention</div>
            <div class="flex space-x-2">
              <button class="px-3 py-1 text-sm text-gray-300 hover:text-white">View Details</button>
              <button
                class="rounded bg-orange-500 px-3 py-1 text-sm text-white hover:bg-orange-600"
              >
                Create Content
              </button>
            </div>
          </div>
        </div>

        <!-- Gaming Tips Pillar -->
        <div class="rounded-xl bg-forest-800 p-6">
          <div class="mb-4 flex items-center justify-between">
            <div class="flex items-center space-x-3">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-500">
                <svg class="h-6 w-6 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z"
                    clip-rule="evenodd"
                  />
                </svg>
              </div>
              <div>
                <h3 class="text-lg font-semibold text-white">Gaming Tips</h3>
                <p class="text-sm text-gray-400">12 Videos • Created 2 months ago</p>
              </div>
            </div>
            <button class="text-gray-400 hover:text-white">
              <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                <path
                  d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
                />
              </svg>
            </button>
          </div>

          <!-- Metrics -->
          <div class="mb-6 grid grid-cols-3 gap-4">
            <div>
              <div class="text-2xl font-bold text-white">203.5K</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +7.3%
              </div>
              <div class="text-xs text-gray-400">Revenue</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">10.1K hrs</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +5.8%
              </div>
              <div class="text-xs text-gray-400">Watch Time</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">92,037</div>
              <div class="flex items-center text-sm text-green-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                +13.7%
              </div>
              <div class="text-xs text-gray-400">Subscribers</div>
            </div>
          </div>

          <!-- Chart Area -->
          <div class="relative mb-4 h-32">
            <svg class="h-full w-full" viewBox="0 0 300 100">
              <defs>
                <linearGradient id="orangeGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" style="stop-color: #f97316; stop-opacity: 0.3" />
                  <stop offset="100%" style="stop-color: #f97316; stop-opacity: 0" />
                </linearGradient>
              </defs>
              <path
                d="M0,90 Q50,85 100,75 T200,60 T300,45"
                stroke="#F97316"
                stroke-width="2"
                fill="none"
              />
              <path
                d="M0,90 Q50,85 100,75 T200,60 T300,45 L300,100 L0,100 Z"
                fill="url(#orangeGradient)"
              />
            </svg>
          </div>

          <!-- Action Buttons -->
          <div class="flex items-center justify-between">
            <div class="text-sm text-gray-400">High engagement from returning viewers</div>
            <div class="flex space-x-2">
              <button class="px-3 py-1 text-sm text-gray-300 hover:text-white">View Details</button>
              <button
                class="rounded bg-orange-500 px-3 py-1 text-sm text-white hover:bg-orange-600"
              >
                Create Content
              </button>
            </div>
          </div>
        </div>
        <!-- Gaming News Pillar -->
        <div class="rounded-xl bg-forest-800 p-6">
          <div class="mb-4 flex items-center justify-between">
            <div class="flex items-center space-x-3">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-500">
                <svg class="h-6 w-6 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"
                  />
                </svg>
              </div>
              <div>
                <h3 class="text-lg font-semibold text-white">Gaming News</h3>
                <p class="text-sm text-gray-400">6 Videos • Created 4 months ago</p>
              </div>
            </div>
            <button class="text-gray-400 hover:text-white">
              <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                <path
                  d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
                />
              </svg>
            </button>
          </div>

          <!-- Metrics -->
          <div class="mb-6 grid grid-cols-3 gap-4">
            <div>
              <div class="text-2xl font-bold text-white">97.2K</div>
              <div class="flex items-center text-sm text-red-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M14.707 12.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 14.586V3a1 1 0 112 0v11.586l2.293-2.293a1 1 0 011.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                -3.8%
              </div>
              <div class="text-xs text-gray-400">Revenue</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">4.3K hrs</div>
              <div class="flex items-center text-sm text-red-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M14.707 12.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 14.586V3a1 1 0 112 0v11.586l2.293-2.293a1 1 0 011.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                -1.2%
              </div>
              <div class="text-xs text-gray-400">Watch Time</div>
            </div>
            <div>
              <div class="text-2xl font-bold text-white">8843</div>
              <div class="flex items-center text-sm text-red-400">
                <svg class="mr-1 h-3 w-3" fill="currentColor" viewBox="0 0 20 20">
                  <path
                    fill-rule="evenodd"
                    d="M14.707 12.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 14.586V3a1 1 0 112 0v11.586l2.293-2.293a1 1 0 011.414 0z"
                    clip-rule="evenodd"
                  />
                </svg>
                -6.5%
              </div>
              <div class="text-xs text-gray-400">Subscribers</div>
            </div>
          </div>

          <!-- Chart Area -->
          <div class="relative mb-4 h-32">
            <svg class="h-full w-full" viewBox="0 0 300 100">
              <defs>
                <linearGradient id="redGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" style="stop-color: #ef4444; stop-opacity: 0.3" />
                  <stop offset="100%" style="stop-color: #ef4444; stop-opacity: 0" />
                </linearGradient>
              </defs>
              <path
                d="M0,60 Q50,65 100,70 T200,75 T300,80"
                stroke="#EF4444"
                stroke-width="2"
                fill="none"
              />
              <path
                d="M0,60 Q50,65 100,70 T200,75 T300,80 L300,100 L0,100 Z"
                fill="url(#redGradient)"
              />
            </svg>
          </div>

          <!-- Action Buttons -->
          <div class="flex items-center justify-between">
            <div class="text-sm text-gray-400">Needs improvement in content strategy</div>
            <div class="flex space-x-2">
              <button class="px-3 py-1 text-sm text-gray-300 hover:text-white">View Details</button>
              <button class="rounded bg-orange-500 px-3 py-1 text-sm text-white hover:bg-orange-600">
                Create Content
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Agent Suggested Pillar -->
      <div class="mt-6 rounded-xl border border-orange-500/20 bg-forest-800 p-6">
        <div class="mb-4 flex items-center justify-between">
          <div class="flex items-center space-x-3">
            <div class="flex h-10 w-10 items-center justify-center rounded-lg overflow-hidden bg-purple-600/20">
              <img
                v-if="selectedAgent.image"
                :src="selectedAgent.image"
                :alt="selectedAgent.name"
                class="h-full w-full object-cover"
              />
              <svg v-else class="h-6 w-6 text-white" fill="currentColor" viewBox="0 0 20 20">
                <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
              </svg>
            </div>
            <div>
              <h3 class="text-lg font-semibold text-white">{{ agentName || selectedAgent.name }} Suggested: Metaverse Coverage</h3>
              <p class="text-sm text-orange-400">NEW</p>
            </div>
          </div>
          <div class="flex space-x-2">
            <button
              class="rounded border border-gray-600 px-3 py-1 text-sm text-gray-300 hover:text-white"
            >
              Dismiss
            </button>
            <button class="rounded bg-orange-500 px-3 py-1 text-sm text-white hover:bg-orange-600">
              Create Pillar
            </button>
          </div>
        </div>
        <p class="text-sm text-gray-300">
          Based on trending topics and your audience interests, consider creating content about
          metaverse gaming and virtual worlds.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useAgentSettings } from '../../composables/useAgentSettings';

// Protect this route with authentication
definePageMeta({
  middleware: 'auth'
})

// Agent settings
const { selectedAgent, agentName } = useAgentSettings()

// Agent data is now handled by the composable

// Content Pillars Analytics Dashboard
// Static data display matching the design from the image
</script>
